@startuml
left to right direction
:Пользователь: --> (Подача сигнала для запуска робота)
:Сервер: --> (Получить кадр)
:Сервер: --> (Определить положение человека)
:Сервер: --> (Распознать жест)
:Сервер: --> (Определить положение робота)
:Сервер: --> (Определить положение диспенсера)
:Сервер: --> (Рассчитать траекторию движения робота)
:Сервер: --> (Отправить управляющий сигнал роботу)
:Сервер: --> (Отправить управляющий сигнал диспенсеру)
:Робот: --> (Выполнение команды от сервера)
:Диспенсер: --> (Выполнение команды от сервера)
:Камера: --> (Передача кадров)
@enduml